export enum AuthErrorCodeEnum {
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
  TOO_MANY_ATTEMPTS_TRY_LATER = 'TOO_MANY_ATTEMPTS_TRY_LATER',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG'
}
